services:
  - type: web
    name: hidrocontrol-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT  # ‚Üê Busca main.py con variable 'app'
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: estados-data
      mountPath: /opt/render/project/src
      sizeGB: 1
