services:
  - type: web
    name: hidrocontrol-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: estados-data
      mountPath: /opt/render/project/src
      sizeGB: 1